build: eliminate unused variable warn on clang 15
```
<...>/small/test/lf_lifo.c:54:6: error: variable 'i' set but not used
    [-Werror,-Wunused-but-set-variable]
        int i = 0;
```

Part of https://github.com/tarantool/tarantool/issues/8110
Fixes #57

(cherry picked from commit 5c3a0880ae4659cb662085563ff0b9eee40565fe)