Fix out of source tarantool build
Moved generated config.h to a binary directory, added it to include
paths for the library itself.

Don't sure how to 'export' this header to make it visible by tarantool.
The workaround I have is described below.

Removed config.h include from small/slab_arena.h because a tarantool
test fails to build in the following way:

 | In file included from /home/alex/p/tarantool-meta/tarantool/src/lib/small/small/slab_cache.h:38,
 |                  from /home/alex/p/tarantool-meta/tarantool/src/lib/small/small/region.h:39,
 |                  from /home/alex/p/tarantool-meta/tarantool/src/lib/core/memory.h:33,
 |                  from /home/alex/p/tarantool-meta/tarantool/test/unit/heap_iterator.c:6:
 | /home/alex/p/tarantool-meta/tarantool/src/lib/small/small/slab_arena.h:36:10: fatal error: config.h: No such file or directory
 |  #include "config.h"
 |           ^~~~~~~~~~

Added it instead to small/slab_arena.c.

I guess this problem may be fixed in a more proper way. A follow up
would be desirable.

This is the regression from 33a267d0ff32130e2fbb8b12b587384bc72538d0
('slab_arena: Enhance slab_arena_create to support madvise hints').