small: fix compilation on macOS 12
Asserts are disabled in the Release build, that leads to:

$ cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_C_FLAGS=-Werror
$ make

[  6%] Building C object src/lib/small/CMakeFiles/small.dir/small/slab_arena.c.o
src/lib/small/small/slab_arena.c:220:9: error: variable 'total' set but not used [-Werror,-Wunused-but-set-variable]
        size_t total = 0;
               ^

(cherry picked from commit 3e5fb2ab3efbf23df211747d9b055910071cb9cd)