test: fix unused variable warning in matras test
test/matras.cc:271:21: error: ‘id’ may be used uninitialized in this function [-Werror=maybe-uninitialized]
  271 |         matras_touch(&local, id);
      |                     ^
test/matras.cc:269:21: note: ‘id’ was declared here
  269 |         matras_id_t id;
      |                     ^